#++++++++++++++++++++++++++++++++++++++
# RabbitMQ Docker container
#++++++++++++++++++++++++++++++++++++++
#
# Official images:
#
#   rabbitmq - official RabbitMQ
#                   https://hub.docker.com/_/rabbitmq/
#
#++++++++++++++++++++++++++++++++++++++

FROM rabbitmq
